/**
 * Codes d'erreur standardisés pour l'API ChapeChape
 * Format: DOMAINE_SOUS_DOMAINE_ACTION_RAISON
 */

// Codes généraux (1000-1999)
exports.GENERAL = {
    BAD_REQUEST: 'GENERAL_BAD_REQUEST',
    NOT_FOUND: 'GENERAL_RESOURCE_NOT_FOUND',
    UNAUTHORIZED: 'GENERAL_UNAUTHORIZED_ACCESS',
    FORBIDDEN: 'GENERAL_FORBIDDEN_ACCESS',
    VALIDATION_ERROR: 'GENERAL_VALIDATION_ERROR',
    SERVER_ERROR: 'GENERAL_SERVER_ERROR',
    SERVICE_UNAVAILABLE: 'GENERAL_SERVICE_UNAVAILABLE',
    TOO_MANY_REQUESTS: 'GENERAL_RATE_LIMIT_EXCEEDED',
    CSRF_ERROR: 'GENERAL_CSRF_ERROR'
};

// Authentification (2000-2999)
exports.AUTH = {
    INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
    INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
    EXPIRED_TOKEN: 'AUTH_EXPIRED_TOKEN',
    MISSING_TOKEN: 'AUTH_MISSING_TOKEN',
    ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
    EMAIL_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
    PASSWORD_WEAK: 'AUTH_PASSWORD_TOO_WEAK',
    PASSWORD_MISMATCH: 'AUTH_PASSWORD_MISMATCH',
    EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED'
};

// Résidences (3000-3999)
exports.RESIDENCE = {
    NOT_FOUND: 'RESIDENCE_NOT_FOUND',
    INVALID_DATA: 'RESIDENCE_INVALID_DATA',
    UNAUTHORIZED_ACCESS: 'RESIDENCE_UNAUTHORIZED_ACCESS',
    MAX_IMAGES_EXCEEDED: 'RESIDENCE_MAX_IMAGES_EXCEEDED',
    UNAVAILABLE: 'RESIDENCE_UNAVAILABLE',
    ALREADY_EXISTS: 'RESIDENCE_ALREADY_EXISTS',
    INVALID_PRICE: 'RESIDENCE_INVALID_PRICE',
    INVALID_LOCATION: 'RESIDENCE_INVALID_LOCATION',
    OPERATION_FAILED: 'RESIDENCE_OPERATION_FAILED'
};

exports.CAPABILITY = {
    REQUIRED: 'CAPABILITY_REQUIRED',
};

// Réservations (4000-4999)
exports.BOOKING = {
    NOT_FOUND: 'BOOKING_NOT_FOUND',
    INVALID_DATES: 'BOOKING_INVALID_DATES',
    DATE_CONFLICT: 'BOOKING_DATE_CONFLICT',
    ALREADY_CONFIRMED: 'BOOKING_ALREADY_CONFIRMED',
    ALREADY_CANCELLED: 'BOOKING_ALREADY_CANCELLED',
    INVALID_STATUS_CHANGE: 'BOOKING_INVALID_STATUS_CHANGE',
    GUEST_LIMIT_EXCEEDED: 'BOOKING_GUEST_LIMIT_EXCEEDED',
    MINIMUM_STAY_NOT_MET: 'BOOKING_MINIMUM_STAY_NOT_MET',
    RESIDENCE_UNAVAILABLE: 'BOOKING_RESIDENCE_UNAVAILABLE',
    UNAUTHORIZED_ACTION: 'BOOKING_UNAUTHORIZED_ACTION'
};

// Modèle Reservation (transitions d’état, atomic updates) — distinct du legacy BOOKING
exports.RESERVATION = {
    NOT_FOUND: 'RESERVATION_NOT_FOUND',
    PAYMENT_REQUIRED: 'RESERVATION_PAYMENT_REQUIRED',
    CONCURRENT_MODIFICATION: 'RESERVATION_CONCURRENT_MODIFICATION',
    INVALID_STATE_TRANSITION: 'RESERVATION_INVALID_STATE_TRANSITION',
    STAY_ACTION_REQUIRED: 'RESERVATION_STAY_ACTION_REQUIRED',
    CHECKIN_TOO_EARLY: 'RESERVATION_CHECKIN_TOO_EARLY',
    DATE_CONFLICT: 'RESERVATION_DATE_CONFLICT',
    APPROVAL_EXPIRED: 'RESERVATION_APPROVAL_EXPIRED',
};

exports.STAY_CREDENTIAL = {
    INVALID: 'STAY_CREDENTIAL_INVALID',
    EXPIRED: 'STAY_CREDENTIAL_EXPIRED',
    CONSUMED: 'STAY_CREDENTIAL_CONSUMED',
    PURPOSE_MISMATCH: 'STAY_CREDENTIAL_PURPOSE_MISMATCH',
    NOT_ELIGIBLE: 'STAY_CREDENTIAL_NOT_ELIGIBLE',
    REGEN_LIMITED: 'STAY_CREDENTIAL_REGEN_LIMITED',
};

exports.INVENTORY = {
    BLOCK_CONFLICT: 'INVENTORY_BLOCK_CONFLICT',
    ALREADY_RESERVED: 'INVENTORY_ALREADY_RESERVED',
    BLOCK_NOT_FOUND: 'BLOCK_NOT_FOUND',
    BLOCK_NOT_OWNED: 'BLOCK_NOT_OWNED',
    INVALID_BLOCK_PERIOD: 'INVALID_BLOCK_PERIOD',
    EXTERNAL_CONFLICT: 'EXTERNAL_RESERVATION_CONFLICT',
    EXTERNAL_NOT_FOUND: 'EXTERNAL_RESERVATION_NOT_FOUND',
    EXTERNAL_NOT_OWNED: 'EXTERNAL_RESERVATION_NOT_OWNED',
    INVALID_EXTERNAL_PERIOD: 'INVALID_EXTERNAL_PERIOD',
    EXTERNAL_NOT_MODIFIABLE: 'EXTERNAL_RESERVATION_NOT_MODIFIABLE',
};

// Paiements (5000-5999)
exports.PAYMENT = {
    FAILED: 'PAYMENT_FAILED',
    ALREADY_PROCESSED: 'PAYMENT_ALREADY_PROCESSED',
    INVALID_AMOUNT: 'PAYMENT_INVALID_AMOUNT',
    METHOD_UNSUPPORTED: 'PAYMENT_METHOD_UNSUPPORTED',
    INVALID_CARD: 'PAYMENT_INVALID_CARD',
    CARD_DECLINED: 'PAYMENT_CARD_DECLINED',
    REFUND_FAILED: 'PAYMENT_REFUND_FAILED',
    INSUFFICIENT_FUNDS: 'PAYMENT_INSUFFICIENT_FUNDS',
    TRANSACTION_EXPIRED: 'PAYMENT_TRANSACTION_EXPIRED',
    PROVIDER_ERROR: 'PAYMENT_PROVIDER_ERROR',
    REFUND_REQUIRED: 'PAYMENT_REFUND_REQUIRED',
};

// Utilisateurs (6000-6999)
exports.USER = {
    NOT_FOUND: 'USER_NOT_FOUND',
    INVALID_DATA: 'USER_INVALID_DATA',
    DUPLICATE_EMAIL: 'USER_DUPLICATE_EMAIL',
    INVALID_ROLE: 'USER_INVALID_ROLE',
    PROFILE_UPDATE_FAILED: 'USER_PROFILE_UPDATE_FAILED',
    ACCOUNT_SUSPENDED: 'USER_ACCOUNT_SUSPENDED',
    PASSWORD_RESET_FAILED: 'USER_PASSWORD_RESET_FAILED'
};

// Partenaires (7000-7999)
exports.PARTNER = {
    NOT_FOUND: 'PARTNER_NOT_FOUND',
    INVALID_DATA: 'PARTNER_INVALID_DATA',
    VERIFICATION_REQUIRED: 'PARTNER_VERIFICATION_REQUIRED',
    APPROVAL_PENDING: 'PARTNER_APPROVAL_PENDING',
    APPROVAL_REJECTED: 'PARTNER_APPROVAL_REJECTED',
    DOCUMENT_REQUIRED: 'PARTNER_DOCUMENT_REQUIRED'
};

// Upload et médias (8000-8999)
exports.MEDIA = {
    UPLOAD_FAILED: 'MEDIA_UPLOAD_FAILED',
    INVALID_TYPE: 'MEDIA_INVALID_TYPE',
    FILE_TOO_LARGE: 'MEDIA_FILE_TOO_LARGE',
    NOT_FOUND: 'MEDIA_NOT_FOUND',
    CORRUPT_FILE: 'MEDIA_CORRUPT_FILE',
    QUOTA_EXCEEDED: 'MEDIA_QUOTA_EXCEEDED'
};

// Notifications (9000-9999)
exports.NOTIFICATION = {
    DELIVERY_FAILED: 'NOTIFICATION_DELIVERY_FAILED',
    INVALID_RECIPIENT: 'NOTIFICATION_INVALID_RECIPIENT',
    TEMPLATE_NOT_FOUND: 'NOTIFICATION_TEMPLATE_NOT_FOUND',
    PREFERENCE_ERROR: 'NOTIFICATION_PREFERENCE_ERROR'
};
